kind: PersistentVolume
apiVersion: v1
metadata:
  name: cam-mongo-pv
  labels:
    type: cam-mongo
spec:
  capacity:
    storage: 15Gi
  accessModes:
     - ReadWriteMany
  nfs:
    server: 10.132.75.98
    path: /icpnfs/data/CAM_db
