kind: PersistentVolume
apiVersion: v1
metadata:
  name: cam-logs-pv
  labels:
    type: cam-logs
spec:
  capacity:
    storage: 10Gi
  accessModes:
     - ReadWriteMany
  nfs:
    server: <nfs-server-ip>
    path: /icpnfs/data/CAM_logs
