kind: PersistentVolume
apiVersion: v1
metadata:
  name: cam-bpd-appdata-pv
  labels:
    type: cam-bpd-appdata
spec:
  capacity:
    storage: 15Gi
  accessModes:
     - ReadWriteMany
  nfs:
    server: <nfs-server-ip>
    path: /icpnfs/data/CAM_BPD_appdate
